import { ChevronDown, Pencil, Plus, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Card, EmptyState, Field, Modal, PageTitle } from '../components/ui'
import { useData } from '../context/DataContext'
import { getCurrentMonth, isInstallmentActiveInMonth } from '../lib/forecast'
import { money } from '../lib/format'
import { groupInstallmentsByAccount, type InstallmentSort } from '../lib/installmentGroups'
import type { Account, AccountType, Expense, ExpenseType, Income, IncomeType, Installment, InstallmentStatus } from '../lib/types'

const currentMonth = getCurrentMonth()
const incomeTypes: Record<IncomeType, string> = { once: 'ครั้งเดียว', monthly: 'ทุกเดือน', fixed_months: 'ตามจำนวนเดือน' }
const expenseTypes: Record<ExpenseType, string> = { once: 'ครั้งเดียว', fixed_months: 'ตามจำนวนเดือน', forever: 'จ่ายประจำ' }
const accountTypes: Record<AccountType, string> = { credit_card: 'บัตรเครดิต', paylater: 'Pay Later', loan: 'สินเชื่อ', other: 'อื่น ๆ' }
const installmentStatuses: Record<InstallmentStatus, string> = { active: 'กำลังผ่อน', completed: 'ผ่อนครบแล้ว', cancelled: 'ยกเลิก' }

function Actions({ onEdit, onDelete }: { onEdit: () => void; onDelete: () => void }) {
  return <div className="flex gap-1"><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" onClick={onEdit} aria-label="แก้ไข"><Pencil size={17}/></button><button className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={onDelete} aria-label="ลบ"><Trash2 size={17}/></button></div>
}

function Switch({ checked, onChange, label = 'ใช้งานอยู่' }: { checked: boolean; onChange: (value: boolean) => void; label?: string }) {
  return <label className="flex items-center gap-3 text-sm font-medium text-slate-700"><input type="checkbox" className="size-4 accent-emerald-700" checked={checked} onChange={(event) => onChange(event.target.checked)}/>{label}</label>
}

function FormButtons({ onClose }: { onClose: () => void }) { return <div className="mt-2 flex justify-end gap-2"><button className="btn-secondary" type="button" onClick={onClose}>ยกเลิก</button><button className="btn-primary" type="submit">บันทึกขึ้น Cloud</button></div> }

export function IncomesPage() {
  const { incomes, save, remove } = useData()
  const [editing, setEditing] = useState<Income | null | undefined>(undefined)
  const close = () => setEditing(undefined)
  const deleteItem = async (item: Income) => { if (window.confirm(`ลบ “${item.name}” ใช่ไหม?`)) await remove('incomes', item.id) }
  return <><PageTitle title="รายรับ" detail="เงินเดือน โบนัส และรายได้เสริมที่เข้ามาตามรอบ" action={<button className="btn-primary" onClick={() => setEditing(null)}><Plus size={18}/>เพิ่มรายรับ</button>}/><Card className="p-4 sm:p-6">{incomes.length ? <div className="grid gap-2">{incomes.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-slate-100 p-4"><div><div className="flex items-center gap-2"><p className="font-semibold text-slate-900">{item.name}</p>{!item.isActive && <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-400">พักไว้</span>}</div><p className="mt-1 text-xs text-slate-400">{incomeTypes[item.type]} · เริ่ม {item.startMonth}{item.receiveDay ? ` · รับวันที่ ${item.receiveDay}` : ''}</p></div><div className="flex items-center gap-3"><strong className="text-emerald-700">+{money(item.amount)}</strong><Actions onEdit={() => setEditing(item)} onDelete={() => deleteItem(item)}/></div></div>)}</div> : <EmptyState title="ยังไม่มีรายรับ" detail="เพิ่มเงินเดือนหรือรายได้ก้อนแรกของคุณ"/>}</Card>{editing !== undefined && <IncomeModal value={editing} onClose={close} onSave={async (payload) => { await save('incomes', payload, editing?.id); close() }}/>}</>
}

function IncomeModal({ value, onClose, onSave }: { value: Income | null; onClose: () => void; onSave: (value: Omit<Income, 'id' | 'createdAt' | 'updatedAt'>) => Promise<void> }) {
  const [form, setForm] = useState({ name: value?.name ?? '', amount: value?.amount ?? 0, type: value?.type ?? 'monthly' as IncomeType, startMonth: value?.startMonth ?? currentMonth, endMonth: value?.endMonth ?? '', repeatMonths: value?.repeatMonths ?? 1, receiveDay: value?.receiveDay ?? '', isActive: value?.isActive ?? true, note: value?.note ?? '' })
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await onSave({ ...form, endMonth: form.endMonth || null, repeatMonths: form.type === 'fixed_months' ? Number(form.repeatMonths) : null, receiveDay: form.receiveDay === '' ? null : Number(form.receiveDay), amount: Number(form.amount) }) }
  return <Modal title={value ? 'แก้ไขรายรับ' : 'เพิ่มรายรับ'} onClose={onClose}><form className="grid gap-4" onSubmit={submit}><Field label="ชื่อรายรับ"><input className="field" required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="เช่น เงินเดือน"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="จำนวนเงิน"><input className="field" required type="number" min="0.01" step="0.01" value={form.amount || ''} onChange={(e) => setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="รูปแบบ"><select className="field" value={form.type} onChange={(e) => setForm({...form,type:e.target.value as IncomeType})}>{Object.entries(incomeTypes).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="เดือนเริ่มต้น"><input className="field" required type="month" value={form.startMonth} onChange={(e) => setForm({...form,startMonth:e.target.value})}/></Field>{form.type === 'fixed_months' ? <Field label="จำนวนเดือน"><input className="field" required type="number" min="1" value={form.repeatMonths} onChange={(e) => setForm({...form,repeatMonths:Number(e.target.value)})}/></Field> : form.type === 'monthly' ? <Field label="เดือนสิ้นสุด (ถ้ามี)"><input className="field" type="month" value={form.endMonth} onChange={(e) => setForm({...form,endMonth:e.target.value})}/></Field> : null}</div><Field label="วันที่รับเงิน (ถ้ามี)"><input className="field" type="number" min="1" max="31" value={form.receiveDay} onChange={(e) => setForm({...form,receiveDay:e.target.value === '' ? '' : Number(e.target.value)})}/></Field><Field label="โน้ต"><textarea className="field min-h-20" value={form.note} onChange={(e) => setForm({...form,note:e.target.value})}/></Field><Switch checked={form.isActive} onChange={(isActive) => setForm({...form,isActive})}/><FormButtons onClose={onClose}/></form></Modal>
}

export function ExpensesPage() {
  const { expenses, save, remove } = useData()
  const [editing, setEditing] = useState<Expense | null | undefined>(undefined)
  const close = () => setEditing(undefined)
  const deleteItem = async (item: Expense) => { if (window.confirm(`ลบ “${item.name}” ใช่ไหม?`)) await remove('expenses', item.id) }
  return <><PageTitle title="รายจ่าย" detail="ค่าใช้จ่ายประจำ รายการครั้งเดียว และค่าใช้จ่ายตามงวด" action={<button className="btn-primary" onClick={() => setEditing(null)}><Plus size={18}/>เพิ่มรายจ่าย</button>}/><Card className="p-4 sm:p-6">{expenses.length ? <div className="grid gap-2">{expenses.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-slate-100 p-4"><div><div className="flex items-center gap-2"><p className="font-semibold text-slate-900">{item.name}</p><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-500">{item.category}</span>{!item.isActive && <span className="text-xs text-slate-400">พักไว้</span>}</div><p className="mt-1 text-xs text-slate-400">{expenseTypes[item.type]} · เริ่ม {item.startMonth}</p></div><div className="flex items-center gap-3"><strong className="text-slate-700">{money(item.amount)}</strong><Actions onEdit={() => setEditing(item)} onDelete={() => deleteItem(item)}/></div></div>)}</div> : <EmptyState title="ยังไม่มีรายจ่าย" detail="เริ่มจากค่าเช่า ค่าเน็ต หรือ subscription ประจำ"/>}</Card>{editing !== undefined && <ExpenseModal value={editing} onClose={close} onSave={async (payload) => { await save('expenses', payload, editing?.id); close() }}/>}</>
}

function ExpenseModal({ value, onClose, onSave }: { value: Expense | null; onClose: () => void; onSave: (value: Omit<Expense, 'id' | 'createdAt' | 'updatedAt'>) => Promise<void> }) {
  const [form, setForm] = useState({ name: value?.name ?? '', amount: value?.amount ?? 0, category: value?.category ?? 'ทั่วไป', type: value?.type ?? 'forever' as ExpenseType, startMonth: value?.startMonth ?? currentMonth, repeatMonths: value?.repeatMonths ?? 1, payDay: value?.payDay ?? '', isActive: value?.isActive ?? true, note: value?.note ?? '' })
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await onSave({ ...form, amount: Number(form.amount), repeatMonths: form.type === 'fixed_months' ? Number(form.repeatMonths) : null, payDay: form.payDay === '' ? null : Number(form.payDay) }) }
  return <Modal title={value ? 'แก้ไขรายจ่าย' : 'เพิ่มรายจ่าย'} onClose={onClose}><form className="grid gap-4" onSubmit={submit}><Field label="ชื่อรายจ่าย"><input className="field" required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="เช่น ค่าเน็ต"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="จำนวนเงิน"><input className="field" required type="number" min="0.01" step="0.01" value={form.amount || ''} onChange={(e) => setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="หมวดหมู่"><input className="field" required value={form.category} onChange={(e) => setForm({...form,category:e.target.value})}/></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="รูปแบบ"><select className="field" value={form.type} onChange={(e) => setForm({...form,type:e.target.value as ExpenseType})}>{Object.entries(expenseTypes).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="เดือนเริ่มต้น"><input className="field" required type="month" value={form.startMonth} onChange={(e) => setForm({...form,startMonth:e.target.value})}/></Field></div>{form.type === 'fixed_months' && <Field label="จำนวนเดือน"><input className="field" required type="number" min="1" value={form.repeatMonths} onChange={(e) => setForm({...form,repeatMonths:Number(e.target.value)})}/></Field>}<Field label="วันที่จ่าย (ถ้ามี)"><input className="field" type="number" min="1" max="31" value={form.payDay} onChange={(e) => setForm({...form,payDay:e.target.value === '' ? '' : Number(e.target.value)})}/></Field><Field label="โน้ต"><textarea className="field min-h-20" value={form.note} onChange={(e) => setForm({...form,note:e.target.value})}/></Field><Switch checked={form.isActive} onChange={(isActive) => setForm({...form,isActive})}/><FormButtons onClose={onClose}/></form></Modal>
}

export function AccountsPage() {
  const { accounts, installments, save, remove } = useData()
  const [editing, setEditing] = useState<Account | null | undefined>(undefined)
  const summaries = useMemo(() => new Map(accounts.map((account) => { const active = installments.filter((item) => item.accountId === account.id && isInstallmentActiveInMonth(item, currentMonth)); return [account.id, { total: active.reduce((sum,item) => sum + item.monthlyAmount, 0), count: active.length }] })), [accounts, installments])
  const close = () => setEditing(undefined)
  const deleteItem = async (item: Account) => { const linked = installments.some((installment) => installment.accountId === item.id); if (linked) return window.alert('บัญชีนี้ยังมีรายการผูกอยู่ กรุณาลบหรือย้ายรายการผ่อนก่อน'); if (window.confirm(`ลบ “${item.name}” ใช่ไหม?`)) await remove('accounts', item.id) }
  return <><PageTitle title="บัญชีและช่องทางผ่อน" detail="บัตรเครดิต Pay Later และสินเชื่อที่ใช้ผ่อนชำระ" action={<button className="btn-primary" onClick={() => setEditing(null)}><Plus size={18}/>เพิ่มบัญชี</button>}/>{accounts.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{accounts.map((item) => <Card key={item.id} className="p-5"><div className="flex items-start justify-between"><div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{accountTypes[item.type]}</span><h2 className="mt-3 text-lg font-bold text-slate-900">{item.name}</h2></div><Actions onEdit={() => setEditing(item)} onDelete={() => deleteItem(item)}/></div><div className="mt-6 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-400">ยอดเดือนนี้</p><p className="mt-1 font-bold">{money(summaries.get(item.id)?.total ?? 0)}</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-400">รายการ active</p><p className="mt-1 font-bold">{summaries.get(item.id)?.count ?? 0} รายการ</p></div></div><p className="mt-4 text-xs text-slate-400">ตัดรอบวันที่ {item.statementDay ?? '—'} · ครบกำหนดวันที่ {item.paymentDueDay ?? '—'}</p></Card>)}</div> : <Card className="p-6"><EmptyState title="ยังไม่มีบัญชีหรือช่องทางผ่อน" detail="เพิ่ม Shopee, Kbank หรือ Pay Later ก่อนสร้างรายการผ่อน"/></Card>}{editing !== undefined && <AccountModal value={editing} onClose={close} onSave={async (payload) => { await save('accounts', payload, editing?.id); close() }}/>}</>
}

function AccountModal({ value, onClose, onSave }: { value: Account | null; onClose: () => void; onSave: (value: Omit<Account, 'id' | 'createdAt' | 'updatedAt'>) => Promise<void> }) {
  const [form, setForm] = useState({ name: value?.name ?? '', type: value?.type ?? 'credit_card' as AccountType, statementDay: value?.statementDay ?? '', paymentDueDay: value?.paymentDueDay ?? '', isActive: value?.isActive ?? true, note: value?.note ?? '' })
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await onSave({ ...form, statementDay: form.statementDay === '' ? null : Number(form.statementDay), paymentDueDay: form.paymentDueDay === '' ? null : Number(form.paymentDueDay) }) }
  return <Modal title={value ? 'แก้ไขบัญชี' : 'เพิ่มบัญชี'} onClose={onClose}><form className="grid gap-4" onSubmit={submit}><Field label="ชื่อบัญชี / ช่องทาง"><input className="field" required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="เช่น Shopee"/></Field><Field label="ประเภท"><select className="field" value={form.type} onChange={(e) => setForm({...form,type:e.target.value as AccountType})}>{Object.entries(accountTypes).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="วันตัดรอบ"><input className="field" type="number" min="1" max="31" value={form.statementDay} onChange={(e) => setForm({...form,statementDay:e.target.value === '' ? '' : Number(e.target.value)})}/></Field><Field label="วันครบกำหนด"><input className="field" type="number" min="1" max="31" value={form.paymentDueDay} onChange={(e) => setForm({...form,paymentDueDay:e.target.value === '' ? '' : Number(e.target.value)})}/></Field></div><Field label="โน้ต"><textarea className="field min-h-20" value={form.note} onChange={(e) => setForm({...form,note:e.target.value})}/></Field><Switch checked={form.isActive} onChange={(isActive) => setForm({...form,isActive})}/><FormButtons onClose={onClose}/></form></Modal>
}

export function InstallmentsPage() {
  const { installments, accounts, save, remove } = useData()
  const [editing, setEditing] = useState<Installment | null | undefined>(undefined)
  const [sort, setSort] = useState<InstallmentSort>('name_asc')
  const [collapsedGroups, setCollapsedGroups] = useState<Set<string>>(new Set())
  const groups = useMemo(() => groupInstallmentsByAccount(installments, accounts, sort), [installments, accounts, sort])
  const close = () => setEditing(undefined)
  const deleteItem = async (item: Installment) => { if (window.confirm(`ลบ “${item.name}” ใช่ไหม?`)) await remove('installments', item.id) }
  const toggleCollapsed = (accountId: string) => setCollapsedGroups((current) => {
    const next = new Set(current)
    if (next.has(accountId)) next.delete(accountId)
    else next.add(accountId)
    return next
  })
  return <>
    <PageTitle title="รายการผ่อน" detail="แยกรายการตามบัตรหรือช่องทางผ่อน เพื่อดูภาระของแต่ละบัญชีชัดขึ้น" action={<div className="flex flex-wrap items-center gap-2"><select aria-label="เรียงรายการในกลุ่ม" className="field w-auto" value={sort} onChange={(event) => setSort(event.target.value as InstallmentSort)}><option value="name_asc">ชื่อ ก–ฮ</option><option value="name_desc">ชื่อ ฮ–ก</option><option value="amount_asc">ยอดน้อย → มาก</option><option value="amount_desc">ยอดมาก → น้อย</option></select><button disabled={!accounts.length} className="btn-primary" onClick={() => setEditing(null)}><Plus size={18}/>เพิ่มรายการผ่อน</button></div>}/>
    {!accounts.length && <p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">เพิ่มบัญชีหรือช่องทางผ่อนก่อน แล้วจึงสร้างรายการผ่อนได้</p>}
    {installments.length ? <div className="grid gap-5">{groups.map((group) => {
      const isCollapsed = collapsedGroups.has(group.accountId)
      return <Card key={group.accountId} className="overflow-hidden"><div className={`flex flex-col gap-3 border-b px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5 ${group.isOrphan ? 'border-amber-100 bg-amber-50' : 'border-slate-100 bg-slate-50/70'}`}><div className="flex items-center gap-3"><button className="grid size-9 shrink-0 place-items-center rounded-xl bg-white text-slate-500 shadow-sm hover:text-slate-900" onClick={() => toggleCollapsed(group.accountId)} aria-label={`${isCollapsed ? 'ขยาย' : 'พับ'}กลุ่ม ${group.accountName}`}><ChevronDown size={18} className={`transition-transform ${isCollapsed ? '-rotate-90' : ''}`}/></button><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold text-slate-900">{group.accountName}</h2><span className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-slate-500 shadow-sm">{group.accountType === 'unknown' ? 'ข้อมูลเก่า' : accountTypes[group.accountType]}</span></div><p className="mt-1 text-xs text-slate-400">ทั้งหมด {group.installments.length} รายการ · กำลังผ่อน {group.activeCount} รายการ</p></div></div><div className="pl-12 sm:pl-0 sm:text-right"><p className="text-xs text-slate-400">ยอดรวมที่กำลังผ่อน</p><p className="mt-1 text-lg font-bold text-slate-900">{money(group.activeMonthlyTotal)}/เดือน</p></div></div>{!isCollapsed && <div className="grid gap-2 p-3 sm:p-4">{group.installments.map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-2xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900">{item.name || 'รายการไม่ทราบชื่อ'}</p><span className={`rounded-full px-2 py-0.5 text-xs ${item.status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{installmentStatuses[item.status] ?? 'ไม่ทราบสถานะ'}</span></div><p className="mt-1 text-xs text-slate-400">{item.totalMonths || '—'} เดือน · เริ่ม {item.firstPaymentMonth || '—'}</p></div><div className="flex items-center justify-between gap-3 sm:justify-end"><strong className="text-slate-800">{money(Number.isFinite(item.monthlyAmount) ? item.monthlyAmount : 0)}/เดือน</strong><Actions onEdit={() => setEditing(item)} onDelete={() => deleteItem(item)}/></div></div>)}</div>}</Card>
    })}</div> : <Card className="p-6"><EmptyState title="ยังไม่มีรายการผ่อน" detail="เพิ่มรายการพร้อมจำนวนงวด ระบบจะคำนวณเดือนสิ้นสุดให้อัตโนมัติ"/></Card>}
    {editing !== undefined && (
      <InstallmentModal accounts={accounts} value={editing} onClose={close} onSave={async (payload) => { await save('installments', payload, editing?.id); close() }}/>
    )}
  </>
}

function InstallmentModal({ accounts, value, onClose, onSave }: { accounts: Account[]; value: Installment | null; onClose: () => void; onSave: (value: Omit<Installment, 'id' | 'createdAt' | 'updatedAt'>) => Promise<void> }) {
  const [form, setForm] = useState({ accountId: value?.accountId ?? accounts[0]?.id ?? '', name: value?.name ?? '', monthlyAmount: value?.monthlyAmount ?? 0, totalMonths: value?.totalMonths ?? 1, firstPaymentMonth: value?.firstPaymentMonth ?? currentMonth, paymentDay: value?.paymentDay ?? '', status: value?.status ?? 'active' as InstallmentStatus, note: value?.note ?? '' })
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await onSave({ ...form, monthlyAmount: Number(form.monthlyAmount), totalMonths: Number(form.totalMonths), paymentDay: form.paymentDay === '' ? null : Number(form.paymentDay) }) }
  return <Modal title={value ? 'แก้ไขรายการผ่อน' : 'เพิ่มรายการผ่อน'} onClose={onClose}><form className="grid gap-4" onSubmit={submit}><Field label="บัญชี / ช่องทาง"><select className="field" required value={form.accountId} onChange={(e) => setForm({...form,accountId:e.target.value})}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="ชื่อรายการ"><input className="field" required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})} placeholder="เช่น มือถือ"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="ยอดต่อเดือน"><input className="field" required type="number" min="0.01" step="0.01" value={form.monthlyAmount || ''} onChange={(e) => setForm({...form,monthlyAmount:Number(e.target.value)})}/></Field><Field label="จำนวนเดือน"><input className="field" required type="number" min="1" value={form.totalMonths} onChange={(e) => setForm({...form,totalMonths:Number(e.target.value)})}/></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="เดือนที่เริ่มจ่าย"><input className="field" required type="month" value={form.firstPaymentMonth} onChange={(e) => setForm({...form,firstPaymentMonth:e.target.value})}/></Field><Field label="วันที่จ่าย"><input className="field" type="number" min="1" max="31" value={form.paymentDay} onChange={(e) => setForm({...form,paymentDay:e.target.value === '' ? '' : Number(e.target.value)})}/></Field></div><Field label="สถานะ"><select className="field" value={form.status} onChange={(e) => setForm({...form,status:e.target.value as InstallmentStatus})}>{Object.entries(installmentStatuses).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="โน้ต"><textarea className="field min-h-20" value={form.note} onChange={(e) => setForm({...form,note:e.target.value})}/></Field><FormButtons onClose={onClose}/></form></Modal>
}
